# Generated by Django 6.0.6 on 2026-07-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginevent',
            name='username',
            field=models.CharField(),
        ),
    ]
